name: cammon
description: mobile as webcam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  camerawesome: ^2.4.0
  ffmpeg_cli: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shadcn_ui: ^0.27.0
  usb: ^0.2.0
  usb_serial: ^0.5.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
